package:
  name: ghscan
  version: "0.2.0"
  epoch: 0
  description: Scan Workflow logs for IOCs from the tj-actions/changed-files breach
  copyright:
    - license: Apache-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/ghscan
      expected-commit: ddfc3219fbf912d17c20607226c74d273af9de83
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/ghscan
      output: ghscan

test:
  pipeline:
    - name: Verify ghscan version
      runs: |
        ghscan -h

update:
  enabled: true
  github:
    identifier: chainguard-dev/ghscan
    strip-prefix: v
